const colors = require('tailwindcss/colors');

module.exports = {
  content: [
    "./public/**/*.{html,php}",
    "./js/**/*.js"
  ],
  theme: {
    colors: {
      inherit: colors.inherit,
      current: colors.current,
      transparent: 'transparent',

      white: colors.white,
      black: colors.black,

      slate: colors.slate,
      zinc: colors.zinc,
      neutral: colors.neutral,
      stone: colors.stone,
      amber: colors.amber,
      lime: colors.lime,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      indigo: colors.indigo,
      violet: colors.violet,
      fuchsia: colors.fuchsia,
      rose: colors.rose,
      blue: colors.blue,
      purple: colors.purple,
      pink: colors.pink,
      yellow: colors.yellow,
      grey: colors.gray,
    },
    fontFamily: {
      sans: ['Brown', 'sans-serif'],
      serif: ['MillerBanner', 'serif'],
      arial: 'Arial, Helvetica, sans-serif',
      century: '"Century Gothic", CenturyGothic, AppleGothic, sans-serif',
      futura: '"Futura LT", Futura, "Trebuchet MS", Arial, Helvetica, sans-serif',
      helvetica: '"Helvetica Neue", Arial, Helvetica, sans-serif',
      helveticaLight: '"HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Arial, Helvetica, sans-serif',
      geneva: 'Geneva, Tahoma, Verdana, sans-serif',
      georgia: 'Georgia, Palatino, "Palatino Linotype", "Times New Roman", serif',
      goudy: '"Goudy Old Style", Georgia, "Times New Roman", serif',
      palatino: 'Palatino, "Palatino Linotype", Georgia, Times, "Times New Roman", serif',
      tahoma: 'Tahoma, Geneva, Verdana, sans-serif',
      times: 'TimesNewRoman, "Times New Roman", Times, Baskerville, Georgia, serif',
      verdana: 'Verdana, Geneva, Tahoma, sans-serif'
    },
    fontSize: {
      xxs: ['0.5625rem', { lineHeight: '1rem' }],
      xs: ['0.6875rem', { lineHeight: '1rem' }],
      sm: ['0.875rem', { lineHeight: '1.25rem' }],
      base: ['1rem', { lineHeight: '1.5rem' }],
      lg: ['1.125rem', { lineHeight: '1.75rem' }],
      xl: ['1.25rem', { lineHeight: '1.75rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
      '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      '5xl': ['3rem', { lineHeight: '1' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
    },
    screens: {
      sm: '480px',
      md: '768px',
      lg: '1024px',
      xl: '1440px',
      '2xl': '1920px',
    },
    extend: {},
  },
  plugins: [],
}
